// flow-typed signature: b1659484ada016b1ec7e687651d8d094
// flow-typed version: <<STUB>>/cpy-cli_v^2.0.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cpy-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cpy-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cpy-cli/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cpy-cli/cli.js' {
  declare module.exports: $Exports<'cpy-cli/cli'>;
}
