// flow-typed signature: 91ab694beabc7ca9bcdd0785118cdf07
// flow-typed version: <<STUB>>/docz-plugin-babel6_v^0.10.3/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'docz-plugin-babel6'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'docz-plugin-babel6' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'docz-plugin-babel6/dist/index' {
  declare module.exports: any;
}

declare module 'docz-plugin-babel6/dist/index.m' {
  declare module.exports: any;
}

declare module 'docz-plugin-babel6/dist/index.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'docz-plugin-babel6/dist/index.js' {
  declare module.exports: $Exports<'docz-plugin-babel6/dist/index'>;
}
declare module 'docz-plugin-babel6/dist/index.m.js' {
  declare module.exports: $Exports<'docz-plugin-babel6/dist/index.m'>;
}
declare module 'docz-plugin-babel6/dist/index.umd.js' {
  declare module.exports: $Exports<'docz-plugin-babel6/dist/index.umd'>;
}
