// flow-typed signature: 0980a8e9fc146f27f84f1e30370bbb2a
// flow-typed version: <<STUB>>/rollup-plugin-svgo_v^1.0.1/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-svgo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-svgo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'rollup-plugin-svgo/index' {
  declare module.exports: $Exports<'rollup-plugin-svgo'>;
}
declare module 'rollup-plugin-svgo/index.js' {
  declare module.exports: $Exports<'rollup-plugin-svgo'>;
}
