// flow-typed signature: 1e424836429d4bf18c5076357c548d6e
// flow-typed version: <<STUB>>/styled-bootstrap-grid_v^1.0.4/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-bootstrap-grid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-bootstrap-grid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styled-bootstrap-grid/dist/Col' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/Container' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/index' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/injectLayoutBaseCSS' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/Row' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/styled/Col' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/styled/Container' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/styled/ContainerFluid' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/styled/index' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/styled/media' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/styled/Row' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/ThemeProvider' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/dist/utils/buildProps' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/example/src/App' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/example/src/App.test' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/example/src/index' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/example/src/registerServiceWorker' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/src/Col' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/src/Container' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/src/index' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/src/injectLayoutBaseCSS' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/src/Row' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/src/styled/Col' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/src/styled/Container' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/src/styled/ContainerFluid' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/src/styled/index' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/src/styled/media' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/src/styled/Row' {
  declare module.exports: any;
}

declare module 'styled-bootstrap-grid/src/ThemeProvider' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styled-bootstrap-grid/dist/Col.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/Col'>;
}
declare module 'styled-bootstrap-grid/dist/Container.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/Container'>;
}
declare module 'styled-bootstrap-grid/dist/index.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/index'>;
}
declare module 'styled-bootstrap-grid/dist/injectLayoutBaseCSS.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/injectLayoutBaseCSS'>;
}
declare module 'styled-bootstrap-grid/dist/Row.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/Row'>;
}
declare module 'styled-bootstrap-grid/dist/styled/Col.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/styled/Col'>;
}
declare module 'styled-bootstrap-grid/dist/styled/Container.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/styled/Container'>;
}
declare module 'styled-bootstrap-grid/dist/styled/ContainerFluid.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/styled/ContainerFluid'>;
}
declare module 'styled-bootstrap-grid/dist/styled/index.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/styled/index'>;
}
declare module 'styled-bootstrap-grid/dist/styled/media.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/styled/media'>;
}
declare module 'styled-bootstrap-grid/dist/styled/Row.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/styled/Row'>;
}
declare module 'styled-bootstrap-grid/dist/ThemeProvider.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/ThemeProvider'>;
}
declare module 'styled-bootstrap-grid/dist/utils/buildProps.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/dist/utils/buildProps'>;
}
declare module 'styled-bootstrap-grid/example/src/App.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/example/src/App'>;
}
declare module 'styled-bootstrap-grid/example/src/App.test.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/example/src/App.test'>;
}
declare module 'styled-bootstrap-grid/example/src/index.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/example/src/index'>;
}
declare module 'styled-bootstrap-grid/example/src/registerServiceWorker.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/example/src/registerServiceWorker'>;
}
declare module 'styled-bootstrap-grid/src/Col.jsx' {
  declare module.exports: $Exports<'styled-bootstrap-grid/src/Col'>;
}
declare module 'styled-bootstrap-grid/src/Container.jsx' {
  declare module.exports: $Exports<'styled-bootstrap-grid/src/Container'>;
}
declare module 'styled-bootstrap-grid/src/index.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/src/index'>;
}
declare module 'styled-bootstrap-grid/src/injectLayoutBaseCSS.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/src/injectLayoutBaseCSS'>;
}
declare module 'styled-bootstrap-grid/src/Row.jsx' {
  declare module.exports: $Exports<'styled-bootstrap-grid/src/Row'>;
}
declare module 'styled-bootstrap-grid/src/styled/Col.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/src/styled/Col'>;
}
declare module 'styled-bootstrap-grid/src/styled/Container.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/src/styled/Container'>;
}
declare module 'styled-bootstrap-grid/src/styled/ContainerFluid.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/src/styled/ContainerFluid'>;
}
declare module 'styled-bootstrap-grid/src/styled/index.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/src/styled/index'>;
}
declare module 'styled-bootstrap-grid/src/styled/media.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/src/styled/media'>;
}
declare module 'styled-bootstrap-grid/src/styled/Row.js' {
  declare module.exports: $Exports<'styled-bootstrap-grid/src/styled/Row'>;
}
declare module 'styled-bootstrap-grid/src/ThemeProvider.jsx' {
  declare module.exports: $Exports<'styled-bootstrap-grid/src/ThemeProvider'>;
}
